name: Auto Merge PRs

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready-to-merge'
    steps:
    - name: Auto-merge pull request
      uses: "peter-evans/enable-pull-request-automerge@v2"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

