name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close stale issues and pull requests
      uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
        days-before-stale: 30
        days-before-close: 7

